# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
# Declare set of commands
orbs:
  docker: circleci/docker@2.2.0
# Define a job to be invoked later in a workflow.
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: nguyenhuuchi3006/c-3d-portfolio
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME # Get from Environment Variable in Circle CI Project
          docker-password: DOCKER_PASSWORD # Get from Environment Variable in Circle CI Project
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'

# Orchestrate jobs using workflows
workflows:
  my-pipeline:
    jobs:
      - say-hello
      # only run this job for master branch and say-hello job is completed
      - build-and-push:
          requires:
            - say-hello
          filters:
            branches:
              only:
                - master
