version: '3'
services:
  c-3d-postfolio-app:
    container_name: c-3d-postfolio-app
    image: nguyenhuuchi3006/c-3d-portfolio:latest
    build:
      context: ..
      dockerfile: Dockerfile
    env_file: ../.env
    ports:
      - '3000:80'
    restart: always
